# Generated by Django 6.0.6 on 2026-06-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('hours_in_game', models.PositiveIntegerField(default=0, verbose_name='Часы в игре')),
                ('gender', models.CharField(choices=[('Man', 'Мужской'), ('Woman', 'Женский'), ('dont_indicate', 'Не указывать')], default='dont_indicate', max_length=20, verbose_name='Пол')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Аватар')),
                ('games', models.ManyToManyField(blank=True, related_name='extra_profiles', to='profiles.game')),
                ('main_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_profiles', to='profiles.game', verbose_name='Основная игра')),
            ],
        ),
    ]
